"""
Landing AI ADE JSON ingestion module.
"""

import json
import os
import base64
from typing import Dict, List, Optional, Any, Tuple
from pathlib import Path
import requests
from dotenv import load_dotenv
import re
from bs4 import BeautifulSoup

load_dotenv()


INCOME_STATEMENT_FIELD_MAP = {
    "total net sales": [("income_statement", "revenue"), ("income_statement", "total_revenue")],
    "total cost of sales": [("income_statement", "cost_of_goods_sold")],
    "gross margin": [("income_statement", "gross_margin")],
    "research and development": [("income_statement", "research_and_development")],
    "selling, general and administrative": [("income_statement", "selling_general_administrative")],
    "total operating expenses": [("income_statement", "operating_expenses"), ("income_statement", "opex")],
    "operating income": [("income_statement", "operating_income")],
    "other income": [("income_statement", "other_income_expense")],
    "income before provision for income taxes": [("income_statement", "income_before_taxes")],
    "provision for income taxes": [("income_statement", "provision_for_income_taxes")],
    "net income": [("income_statement", "net_income")],
    "basic": [("kpi_table", "eps_basic")],
    "diluted": [("kpi_table", "eps_diluted")],
}

BALANCE_SHEET_FIELD_MAP = {
    "total current assets": [("balance_sheet", "assets.total_current_assets")],
    "total assets": [("balance_sheet", "total_assets")],
    "total current liabilities": [("balance_sheet", "liabilities.total_current_liabilities")],
    "total liabilities": [("balance_sheet", "total_liabilities")],
    "total shareholders' equity": [("balance_sheet", "total_equity")],
}

CASH_FLOW_FIELD_MAP = {
    "cash generated by operating activities": [("cash_flow", "cash_from_operations")],
    "cash generated by investing activities": [("cash_flow", "cash_from_investing")],
    "cash used in financing activities": [("cash_flow", "cash_from_financing")],
    "payments for acquisition of property, plant and equipment": [("cash_flow", "capital_expenditures")],
    "cash paid for income taxes": [("cash_flow", "cash_taxes_paid")],
    "cash, cash equivalents and restricted cash, ending balances": [("cash_flow", "ending_cash_balance")],
}


def _coerce_numeric_fields(data: Dict[str, Any]) -> None:
    """Convert numeric strings in the dictionary to floats in-place."""
    for key, value in list(data.items()):
        if isinstance(value, dict):
            _coerce_numeric_fields(value)
        elif isinstance(value, str):
            parsed = _parse_numeric(value)
            if parsed is not None:
                data[key] = parsed

ABS_VALUE_FIELDS = {"cash_flow.capital_expenditures"}

STOP_WORDS_INCOME_STATEMENT = [
    "net sales by reportable segment",
    "net sales by category",
    "shares used in computing earnings per share"
]

# Try to import Landing AI ADE library
try:
    from landingai_ade import LandingAIADE
    LANDINGAI_ADE_AVAILABLE = True
except ImportError:
    LANDINGAI_ADE_AVAILABLE = False
    LandingAIADE = None


def load_ade_json(file_path: str) -> Dict[str, Any]:
    """
    Load and parse Landing AI ADE JSON file.
    
    Args:
        file_path: Path to the JSON file
    
    Returns:
        Parsed JSON dictionary
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)


def extract_from_pdf(pdf_path: str, api_key: Optional[str] = None) -> Dict[str, Any]:
    """
    Extract structured data from PDF using Landing AI ADE API.
    
    Args:
        pdf_path: Path to the PDF file
        api_key: Landing AI API key (default: from environment)
    
    Returns:
        Extracted JSON dictionary
    """
    # Set API key if provided
    if api_key:
        os.environ["VISION_AGENT_API_KEY"] = api_key
    else:
        api_key = os.getenv("LANDINGAI_API_KEY") or os.getenv("VISION_AGENT_API_KEY")
        if api_key:
            os.environ["VISION_AGENT_API_KEY"] = api_key
    
    if not api_key and not os.getenv("VISION_AGENT_API_KEY"):
        raise ValueError("Landing AI API key not provided. Set LANDINGAI_API_KEY or VISION_AGENT_API_KEY environment variable.")
    
    # Use official library if available
    if LANDINGAI_ADE_AVAILABLE:
        try:
            ade_client = LandingAIADE()
            
            # Parse the document
            parse_response = ade_client.parse(
                document=Path(pdf_path),
                model="dpt-2-latest"
            )
            
            # Convert markdown to structured data
            # The parse_response contains markdown, we need to extract structured data
            # For now, return the markdown and parse it
            result = {
                "markdown": parse_response.markdown,
                "document": {
                    "text": parse_response.markdown,
                    "tables": _extract_tables_from_markdown(parse_response.markdown),
                    "fields": {}
                }
            }
            
            return result
        
        except Exception as e:
            # Fall back to HTTP API if library fails
            print(f"Landing AI ADE library error: {e}, falling back to HTTP API")
            return _extract_from_pdf_http(pdf_path, api_key)
    else:
        # Fall back to HTTP API if library not available
        return _extract_from_pdf_http(pdf_path, api_key)


def extract_from_pdf_bytes(pdf_bytes: bytes, filename: str, api_key: Optional[str] = None) -> Dict[str, Any]:
    """
    Extract structured data from PDF bytes using Landing AI ADE API.
    
    Args:
        pdf_bytes: PDF file content as bytes
        filename: Original filename
        api_key: Landing AI API key (default: from environment)
    
    Returns:
        Extracted JSON dictionary
    """
    # Set API key if provided
    if api_key:
        os.environ["VISION_AGENT_API_KEY"] = api_key
    else:
        api_key = os.getenv("LANDINGAI_API_KEY") or os.getenv("VISION_AGENT_API_KEY")
        if api_key:
            os.environ["VISION_AGENT_API_KEY"] = api_key
    
    if not api_key and not os.getenv("VISION_AGENT_API_KEY"):
        raise ValueError("Landing AI API key not provided. Set LANDINGAI_API_KEY or VISION_AGENT_API_KEY environment variable.")
    
    # Write to temporary file and use library if available
    if LANDINGAI_ADE_AVAILABLE:
        try:
            import tempfile
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                tmp_file.write(pdf_bytes)
                tmp_path = tmp_file.name
            
            try:
                result = extract_from_pdf(tmp_path, api_key)
                return result
            finally:
                # Clean up temp file
                if os.path.exists(tmp_path):
                    os.unlink(tmp_path)
        
        except Exception as e:
            # Fall back to HTTP API if library fails
            print(f"Landing AI ADE library error: {e}, falling back to HTTP API")
            return _extract_from_pdf_bytes_http(pdf_bytes, filename, api_key)
    else:
        # Fall back to HTTP API if library not available
        return _extract_from_pdf_bytes_http(pdf_bytes, filename, api_key)


def _extract_from_pdf_http(pdf_path: str, api_key: Optional[str] = None) -> Dict[str, Any]:
    """Extract data using HTTP API (fallback method)."""
    # Read PDF file
    with open(pdf_path, 'rb') as f:
        pdf_content = f.read()
    
    filename = os.path.basename(pdf_path)
    return _extract_from_pdf_bytes_http(pdf_content, filename, api_key)


def _extract_from_pdf_bytes_http(pdf_bytes: bytes, filename: str, api_key: Optional[str] = None) -> Dict[str, Any]:
    """Extract data using HTTP API (fallback method)."""
    api_key = api_key or os.getenv("LANDINGAI_API_KEY") or os.getenv("VISION_AGENT_API_KEY")
    
    if not api_key:
        raise ValueError("Landing AI API key not provided.")
    
    # Encode PDF to base64
    pdf_base64 = base64.b64encode(pdf_bytes).decode('utf-8')
    
    # Prepare API request - try different possible endpoints
    api_urls = [
        "https://api.landing.ai/v1/ade/parse",
        "https://predict.app.landing.ai/v1/ade/parse",
    ]
    
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "file": {
            "content": pdf_base64,
            "filename": filename
        },
        "parse_options": {
            "output_format": "json",
            "extract_tables": True,
            "extract_figures": False
        }
    }
    
    # Try each endpoint
    for api_url in api_urls:
        try:
            response = requests.post(api_url, headers=headers, json=payload, timeout=300)
            response.raise_for_status()
            
            result = response.json()
            
            # ADE API returns data in different formats, normalize it
            if "data" in result:
                return result["data"]
            elif "result" in result:
                return result["result"]
            elif "extracted_data" in result:
                return result["extracted_data"]
            else:
                # If the response is already the extracted data, return it
                return result
        
        except requests.exceptions.RequestException as e:
            continue
    
    raise Exception(f"Landing AI ADE API error: Unable to connect to any endpoint")


def _extract_tables_from_markdown(markdown: str) -> List[Dict[str, Any]]:
    """Extract tables from markdown/HTML text."""
    tables: List[Dict[str, Any]] = []
    if not markdown:
        return tables

    soup = BeautifulSoup(markdown, "html.parser")
    for table in soup.find_all("table"):
        table_data: List[List[str]] = []
        for row in table.find_all("tr"):
            cells = []
            for cell in row.find_all(["td", "th"]):
                text = cell.get_text(separator=" ", strip=True)
                text = re.sub(r"\s+", " ", text)
                cells.append(text)
            if cells:
                table_data.append(cells)
        if table_data:
            tables.append({"data": table_data})

    return tables


def _populate_financials_from_markdown(markdown: str, normalized: Dict[str, Any]) -> None:
    """Populate normalized structure by parsing HTML tables in markdown."""
    if not markdown:
        return

    tables = _extract_tables_from_markdown(markdown)
    for table in tables:
        rows = table.get("data", [])
        if not rows:
            continue

        header_text = " ".join(" ".join(r).lower() for r in rows[:2])
        if "statement" in header_text and "operations" in header_text:
            _apply_table_mapping(rows, INCOME_STATEMENT_FIELD_MAP, normalized, table_type="income_statement")
        elif "balance sheet" in header_text:
            _apply_table_mapping(rows, BALANCE_SHEET_FIELD_MAP, normalized, table_type="balance_sheet")
        elif "cash flows" in header_text:
            _apply_table_mapping(rows, CASH_FLOW_FIELD_MAP, normalized, table_type="cash_flow")


def _apply_table_mapping(
    rows: List[List[str]],
    mapping: Dict[str, List[Tuple[str, str]]],
    normalized: Dict[str, Any],
    table_type: str,
) -> None:
    for row in rows:
        if not row:
            continue
        label = _normalize_label(row[0])
        if not label:
            continue
        if table_type == "income_statement" and any(stop in label for stop in STOP_WORDS_INCOME_STATEMENT):
            break

        value = _find_numeric_value(row)
        if value is None:
            continue

        for key, targets in mapping.items():
            if key in label:
                for section, field in targets:
                    _assign_value(normalized, section, field, value)
                break


def _normalize_label(label: str) -> str:
    label = label.lower()
    label = label.replace('/', ' ')
    label = label.replace('—', ' ').replace('–', ' ')
    label = re.sub(r"\(.*?\)", " ", label)
    label = label.replace(':', ' ')
    label = re.sub(r"\s+", " ", label)
    return label.strip()


def _find_numeric_value(row: List[str]) -> Optional[float]:
    for cell in row[1:]:
        value = _parse_numeric(cell)
        if value is not None:
            return value
    return None


def _assign_value(normalized: Dict[str, Any], section: str, field: str, value: float) -> None:
    if value is None:
        return

    full_path = f"{section}.{field}"
    if full_path in ABS_VALUE_FIELDS:
        value = abs(value)

    if section == "income_statement":
        normalized["income_statement"][field] = value
    elif section == "kpi_table":
        if field not in normalized["kpi_table"]:
            normalized["kpi_table"][field] = value
    elif section == "balance_sheet":
        if "." in field:
            top, sub = field.split('.', 1)
            normalized["balance_sheet"].setdefault(top, {})[sub] = value
        else:
            normalized["balance_sheet"][field] = value
    elif section == "cash_flow":
        normalized["cash_flow"][field] = value

def normalize_ade_response(ade_response: Dict[str, Any]) -> Dict[str, Any]:
    """
    Normalize Landing AI ADE response to standard format.
    
    Args:
        ade_response: Raw ADE API response
    
    Returns:
        Normalized JSON dictionary
    """
    normalized = {
        "income_statement": {},
        "balance_sheet": {"assets": {}, "liabilities": {}, "equity": {}},
        "cash_flow": {},
        "kpi_table": {},
        "notes": {},
        "index": {}
    }
    
    markdown_sources: List[str] = []
    top_markdown = ade_response.get("markdown")
    if isinstance(top_markdown, str) and top_markdown.strip():
        markdown_sources.append(top_markdown)
    
    # If the response already has our structure and contains data, use it directly
    if "income_statement" in ade_response:
        is_data = ade_response["income_statement"]
        if isinstance(is_data, dict) and is_data:  # Check if not empty
            normalized["income_statement"] = is_data
            _coerce_numeric_fields(normalized["income_statement"])
        elif isinstance(is_data, dict) and not is_data:
            # Empty dict - try to extract from other sources
            pass  # Will try extraction below
        else:
            normalized["income_statement"] = is_data
    
    if "balance_sheet" in ade_response:
        bs_data = ade_response["balance_sheet"]
        if isinstance(bs_data, dict) and bs_data:
            normalized["balance_sheet"] = bs_data
            _coerce_numeric_fields(normalized["balance_sheet"])
    
    if "cash_flow" in ade_response:
        cf_data = ade_response["cash_flow"]
        if isinstance(cf_data, dict) and cf_data:
            normalized["cash_flow"] = cf_data
            _coerce_numeric_fields(normalized["cash_flow"])
    
    if "kpi_table" in ade_response:
        kpi_data = ade_response["kpi_table"]
        if isinstance(kpi_data, dict) and kpi_data:
            normalized["kpi_table"] = kpi_data
            _coerce_numeric_fields(normalized["kpi_table"])
    
    # Try to extract data from common ADE response formats
    if "document" in ade_response:
        doc = ade_response["document"]
        if isinstance(doc, dict):
            doc_markdown = doc.get("markdown")
            if isinstance(doc_markdown, str) and doc_markdown.strip():
                markdown_sources.append(doc_markdown)
            doc_text = doc.get("text")
            if isinstance(doc_text, str) and doc_text.strip():
                markdown_sources.append(doc_text)
        
        # Extract tables (common in financial reports)
        if "tables" in doc:
            for table in doc["tables"]:
                # Try to identify table type and extract data
                table_data = table.get("data", [])
                if table_data:
                    # Extract table data to KPI table
                    extracted = _extract_table_data(table_data)
                    if extracted:
                        normalized["kpi_table"].update(extracted)
                        
                        # Also try to map to income statement if not already populated
                        if not normalized["income_statement"]:
                            for key, value in extracted.items():
                                key_lower = key.lower()
                                if "revenue" in key_lower:
                                    normalized["income_statement"]["revenue"] = value
                                    normalized["income_statement"]["total_revenue"] = value
                                elif "operating" in key_lower and "expense" in key_lower:
                                    normalized["income_statement"]["operating_expenses"] = value
                                    normalized["income_statement"]["opex"] = value
                                elif "net income" in key_lower or "netincome" in key_lower:
                                    normalized["income_statement"]["net_income"] = value
                                elif "ebitda" in key_lower:
                                    normalized["income_statement"]["ebitda"] = value
                                elif "ebit" in key_lower and "ebitda" not in key_lower:
                                    normalized["income_statement"]["ebit"] = value
        
        # Extract text and try to find financial data using regex patterns
        if "text" in doc:
            text = doc["text"]
            normalized["notes"]["raw_text"] = text
            
            # Try to extract financial metrics from text using simple patterns
            # Look for revenue patterns like "Revenue: $10,000,000" or "Total Revenue $10M"
            revenue_patterns = [
                r'revenue[:\s]+\$?([\d,]+(?:\.\d+)?)\s*(?:million|m|billion|b|k|thousand)?',
                r'total\s+revenue[:\s]+\$?([\d,]+(?:\.\d+)?)',
            ]
            for pattern in revenue_patterns:
                match = re.search(pattern, text, re.IGNORECASE)
                if match:
                    value_str = match.group(1).replace(",", "")
                    value = _parse_numeric(value_str)
                    if value and value > 0:
                        normalized["income_statement"]["revenue"] = value
                        normalized["income_statement"]["total_revenue"] = value
                        normalized["kpi_table"]["revenue"] = value
                        break
        
        # Extract fields if available
        if "fields" in doc:
            fields = doc["fields"]
            for field_name, field_value in fields.items():
                field_lower = field_name.lower()
                value = _parse_numeric(field_value)
                if value is not None:
                    # Map common field names to our structure
                    if "revenue" in field_lower:
                        normalized["income_statement"]["revenue"] = value
                        normalized["income_statement"]["total_revenue"] = value
                        normalized["kpi_table"]["revenue"] = value
                    elif "operating" in field_lower and "expense" in field_lower:
                        normalized["income_statement"]["operating_expenses"] = value
                        normalized["income_statement"]["opex"] = value
                    elif "net" in field_lower and "income" in field_lower:
                        normalized["income_statement"]["net_income"] = value
                    elif "ebitda" in field_lower:
                        normalized["income_statement"]["ebitda"] = value
                    elif "asset" in field_lower:
                        normalized["balance_sheet"]["assets"][field_name] = value
                    elif "liability" in field_lower:
                        normalized["balance_sheet"]["liabilities"][field_name] = value
                    elif "equity" in field_lower:
                        normalized["balance_sheet"]["equity"][field_name] = value
    
    
    # Populate financial sections using parsed markdown tables
    for md_content in dict.fromkeys(markdown_sources):
        _populate_financials_from_markdown(md_content, normalized)
    
    # Ensure critical fields exist even if income_statement already has partial data
    if "revenue" not in normalized["income_statement"]:
        for key in [
            "revenue",
            "total_revenue",
            "total net sales",
            "total_net_sales",
            "total_net_sales_(1)",
            "total net sales (1)",
        ]:
            value = normalized["kpi_table"].get(key)
            if value is not None:
                normalized["income_statement"]["revenue"] = value
                normalized["income_statement"]["total_revenue"] = value
                break
    
    if "net_income" not in normalized["income_statement"]:
        for key in ["net_income", "net income"]:
            value = normalized["kpi_table"].get(key)
            if value is not None:
                normalized["income_statement"]["net_income"] = value
                break
    # If we still have empty income_statement but have kpi_table, try to use kpi_table
    if not normalized["income_statement"] and normalized["kpi_table"]:
        kpi_table = normalized["kpi_table"]
        for key, value in kpi_table.items():
            key_lower = str(key).lower()
            if "revenue" in key_lower:
                normalized["income_statement"]["revenue"] = value
                normalized["income_statement"]["total_revenue"] = value
            elif "operating" in key_lower and "expense" in key_lower:
                normalized["income_statement"]["operating_expenses"] = value
                normalized["income_statement"]["opex"] = value
            elif "net" in key_lower and "income" in key_lower:
                normalized["income_statement"]["net_income"] = value
            elif "ebitda" in key_lower:
                normalized["income_statement"]["ebitda"] = value
    
    return normalized


def _extract_table_data(table_data: List[List[str]]) -> Dict[str, float]:
    """Extract key-value pairs from table data."""
    kpis = {}
    
    if not table_data:
        return kpis
    
    # Handle different table structures
    # Skip header row if it looks like a header (e.g., contains "Metric", "Value", etc.)
    start_row = 0
    if table_data and len(table_data) > 0:
        first_row = [str(cell).lower() for cell in table_data[0]]
        if any(header in first_row for header in ["metric", "item", "description", "account", "line item"]):
            start_row = 1
    
    for row in table_data[start_row:]:
        if not row or len(row) < 2:
            continue
        
        # Try first column as key, second as value
        key = str(row[0]).strip()
        value_str = str(row[1]).strip()
        
        # Skip if key is empty or looks like a number
        if not key or key.replace(",", "").replace(".", "").replace("-", "").isdigit():
            continue
        
        value = _parse_numeric(value_str)
        if value is not None:
            # Normalize key name
            key_normalized = key.lower().replace(" ", "_").replace("-", "_").replace(":", "")
            kpis[key_normalized] = value
            # Also keep original key for flexibility
            kpis[key] = value
    
    return kpis


def _parse_numeric(value: Any) -> Optional[float]:
    """Parse a value to float, handling various formats."""
    if isinstance(value, (int, float)):
        return float(value)

    if isinstance(value, str):
        raw = value
        value = value.replace('$', '').replace(',', '')
        value = value.replace('–', '-').replace('—', '-')
        value = value.replace('(', '-').replace(')', '')
        value = value.strip()

        if not value:
            return None

        if value.endswith('%'):
            try:
                return float(value[:-1]) / 100
            except ValueError:
                cleaned = re.sub(r'[^0-9\.-]', '', value[:-1])
                return float(cleaned) / 100 if cleaned else None

        try:
            return float(value)
        except ValueError:
            cleaned = re.sub(r'[^0-9\.-]', '', value)
            if cleaned in ('', '-', '.'):  # still not parseable
                return None
            try:
                return float(cleaned)
            except ValueError:
                return None

    return None


def validate_report_json(report_json: Dict[str, Any]) -> Tuple[bool, List[str]]:
    """
    Validate that report JSON has required structure.
    
    Args:
        report_json: Report JSON dictionary
    
    Returns:
        Tuple of (is_valid, list_of_errors)
    """
    errors = []
    required_sections = ['income_statement', 'balance_sheet', 'cash_flow']
    
    for section in required_sections:
        if section not in report_json:
            errors.append(f"Missing required section: {section}")
    
    if 'kpi_table' not in report_json:
        errors.append("Missing required section: kpi_table")
    
    return (len(errors) == 0, errors)


def extract_kpis(report_json: Dict[str, Any]) -> Dict[str, float]:
    """
    Extract KPIs from report JSON.
    
    Args:
        report_json: Report JSON dictionary
    
    Returns:
        Dictionary of KPI names and values
    """
    kpis = {}
    
    # First, extract from kpi_table
    if 'kpi_table' in report_json:
        kpi_table = report_json['kpi_table']
        if isinstance(kpi_table, dict):
            # Convert all values to float if possible
            for key, value in kpi_table.items():
                if isinstance(value, (int, float)):
                    kpis[key] = float(value)
                elif isinstance(value, str):
                    # Try to parse numeric strings
                    try:
                        # Remove common formatting
                        cleaned = value.replace("$", "").replace(",", "").strip()
                        kpis[key] = float(cleaned)
                    except (ValueError, AttributeError):
                        pass
        elif isinstance(kpi_table, list):
            for item in kpi_table:
                if isinstance(item, dict) and 'name' in item and 'value' in item:
                    try:
                        value = item['value']
                        if isinstance(value, (int, float)):
                            kpis[item['name']] = float(value)
                        elif isinstance(value, str):
                            cleaned = value.replace("$", "").replace(",", "").strip()
                            kpis[item['name']] = float(cleaned)
                    except (ValueError, TypeError):
                        pass
    
    # Also extract from income statement (with case-insensitive matching)
    if 'income_statement' in report_json:
        is_data = report_json['income_statement']
        
        # Handle different data structures
        if isinstance(is_data, dict):
            # Common field names (try exact match first, then case-insensitive)
            field_mappings = {
                'revenue': ['revenue', 'total_revenue', 'Revenue', 'Total Revenue', 'REVENUE', 'TOTAL_REVENUE'],
                'total_revenue': ['total_revenue', 'revenue', 'Total Revenue', 'Revenue', 'TOTAL_REVENUE', 'REVENUE'],
                'operating_expenses': ['operating_expenses', 'opex', 'Operating Expenses', 'OpEx', 'OPERATING_EXPENSES'],
                'opex': ['opex', 'operating_expenses', 'OpEx', 'Operating Expenses', 'OPEX'],
                'ebitda': ['ebitda', 'EBITDA', 'Ebitda'],
                'ebit': ['ebit', 'EBIT', 'Ebit'],
                'net_income': ['net_income', 'Net Income', 'netincome', 'NET_INCOME', 'NetIncome'],
                'cogs': ['cogs', 'cost_of_goods_sold', 'COGS', 'Cost of Goods Sold', 'cost_of_goods_sold'],
                'cost_of_goods_sold': ['cost_of_goods_sold', 'cogs', 'Cost of Goods Sold', 'COGS'],
                'depreciation': ['depreciation', 'Depreciation', 'DEPRECIATION'],
                'amortization': ['amortization', 'Amortization', 'AMORTIZATION'],
                'interest_expense': ['interest_expense', 'Interest Expense', 'interest', 'INTEREST_EXPENSE'],
                'tax_rate': ['tax_rate', 'Tax Rate', 'taxrate', 'TAX_RATE']
            }
            
            # Try exact matches first
            for standard_name, possible_names in field_mappings.items():
                if standard_name not in kpis:  # Don't override if already found
                    for name in possible_names:
                        if name in is_data:
                            value = is_data[name]
                            if isinstance(value, (int, float)) and not (isinstance(value, bool)):
                                kpis[standard_name] = float(value)
                                break
                            elif isinstance(value, str):
                                try:
                                    cleaned = value.replace("$", "").replace(",", "").replace("(", "-").replace(")", "").strip()
                                    if cleaned:
                                        kpis[standard_name] = float(cleaned)
                                        break
                                except (ValueError, AttributeError):
                                    pass
            
            # Also try case-insensitive search for any numeric fields
            if not kpis:
                for key, value in is_data.items():
                    if isinstance(value, (int, float)) and not isinstance(value, bool):
                        key_lower = key.lower().replace(" ", "_").replace("-", "_")
                        # Map common variations
                        if 'revenue' in key_lower and 'revenue' not in kpis:
                            kpis['revenue'] = float(value)
                        elif 'opex' in key_lower or ('operating' in key_lower and 'expense' in key_lower):
                            if 'opex' not in kpis:
                                kpis['opex'] = float(value)
                        elif 'net_income' in key_lower or 'netincome' in key_lower:
                            if 'net_income' not in kpis:
                                kpis['net_income'] = float(value)
        
        elif isinstance(is_data, list):
            # Handle list format (array of items)
            for item in is_data:
                if isinstance(item, dict):
                    # Try to extract from list items
                    if 'name' in item and 'value' in item:
                        name = item['name'].lower().replace(" ", "_")
                        try:
                            value = item['value']
                            if isinstance(value, (int, float)):
                                kpis[name] = float(value)
                            elif isinstance(value, str):
                                cleaned = value.replace("$", "").replace(",", "").strip()
                                kpis[name] = float(cleaned)
                        except (ValueError, TypeError):
                            pass
    
    # Extract from balance sheet
    if 'balance_sheet' in report_json:
        bs_data = report_json['balance_sheet']
        # Try to extract from nested structure (assets, liabilities, equity)
        if isinstance(bs_data, dict):
            # Check if it's the nested structure
            if 'assets' in bs_data and isinstance(bs_data['assets'], dict):
                # Sum up total assets
                total_assets = sum(
                    v for k, v in bs_data['assets'].items() 
                    if isinstance(v, (int, float)) and 'total' not in k.lower()
                )
                if 'total_assets' in bs_data.get('assets', {}):
                    total_assets = bs_data['assets']['total_assets']
                if total_assets > 0:
                    kpis['total_assets'] = float(total_assets)
            
            # Direct fields
            common_bs_fields = ['total_assets', 'total_liabilities', 'total_equity',
                              'current_assets', 'current_liabilities']
            for field in common_bs_fields:
                if field in bs_data and field not in kpis:
                    value = bs_data[field]
                    if isinstance(value, (int, float)):
                        kpis[field] = float(value)
    
    # Extract from cash flow
    if 'cash_flow' in report_json:
        cf_data = report_json['cash_flow']
        cash_flow_fields = ['depreciation', 'amortization', 'capex', 'capital_expenditures',
                           'free_cash_flow', 'cash_from_operations', 'operating_cash_flow']
        for field in cash_flow_fields:
            if field in cf_data and field not in kpis:
                value = cf_data[field]
                if isinstance(value, (int, float)):
                    kpis[field] = float(value)
    
    return kpis


def get_field_reference(report_json: Dict[str, Any], field_name: str) -> Optional[Dict[str, Any]]:
    """
    Get document reference for a field (page/paragraph mapping).
    
    Args:
        report_json: Report JSON dictionary
        field_name: Name of the field to look up
    
    Returns:
        Reference dictionary with page/paragraph info, or None
    """
    if 'index' not in report_json:
        return None
    
    index = report_json['index']
    if isinstance(index, dict) and field_name in index:
        return index[field_name]
    
    return None

